if(CMAKE_VERSION VERSION_LESS 2.8.12)
function(add_compile_options)
  add_definitions(${ARGV})
endfunction()
endif()

function(enable_cxx11_support)
  include(CheckCXXSourceCompiles)
  CHECK_CXX_SOURCE_COMPILES("#include <memory>; int main() {auto p = std::make_shared<int>(0); return *p; }" already_supported)
  if(NOT already_supported)
    include(CheckCXXCompilerFlag)
    set(test_flags -std=c++11 -std=c++0x)
    foreach(f ${test_flags})
      CHECK_CXX_COMPILER_FLAG("${f}" supported)
      if(supported)
        set(flags "${f}")
        break()
      endif()
    endforeach()
    if(NOT flags)
      message(FATAL_ERROR "Compiler ${CMAKE_CXX_COMPILER} has no C++11 support.")
    else()
      add_compile_options(${flags})
    endif()
  endif()
endfunction()

enable_cxx11_support()